# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/SingleT_CPU/SingleT_CPU.cache/wt [current_project]
set_property parent.project_path D:/SingleT_CPU/SingleT_CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/selector3.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/selector32_5.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/signExtend.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/selector5.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/selector32.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/PCAddNum.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/PcAddFour.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/PC.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/Jump.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/InsMEM.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/DataMEM.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/ControlUnit.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/ALU.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/RegisterFile.v
  D:/SingleT_CPU/SingleT_CPU.srcs/sources_1/new/Main.v
}
synth_design -top Main -part xc7a35tcpg236-1
write_checkpoint -noxdef Main.dcp
catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
